FROM python:3.8

WORKDIR /home

RUN apt-get update && \
    apt-get install -y python3-dev python3-pip build-essential vim && \
    pip install --upgrade pip && \
    pip install pika && \
    pip install confluent-kafka && \
    pip install pytest && \
    pip install pytest-cov && \
    pip install coverage


RUN mkdir /src
COPY src/ /home/src
COPY tests/ /home/tests
COPY runtests.sh /home/runtests.sh

#CMD ["sleep", "infinity"]
CMD ["/bin/bash", "/home/runtests.sh"]
