version: '3'
services:
  rabbitmq:
    container_name: my_rabbitmq_container
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mynetwork

  zookeeper:
    container_name: my_zookeeper_container
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - mynetwork
  
  kafka:
    container_name: my_kafka_container
    image: confluentinc/cp-kafka:7.4.4
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./src:/home/src
    depends_on:
      - rabbitmq
      - kafka
      - zookeeper
    networks:
      - mynetwork

  test:
    build:
      context: .
      dockerfile: Dockerfile.Intgtest
    volumes:
      - ./src:/home/src
    depends_on:
      - rabbitmq
      - kafka
      - zookeeper
      - app
    networks:
      - mynetwork

networks:
  mynetwork: