FROM python:3.8

WORKDIR /home

RUN apt-get update && \
    apt-get install -y python3-dev python3-pip build-essential vim && \
    pip install --upgrade pip && \
    pip install pika && \
    pip install confluent-kafka

RUN mkdir /src
COPY src/ /home/src
COPY tests/ /home/tests

#CMD ["sleep", "infinity"]
CMD ["python", "/home/tests/integration_tests.py"]